kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc2
  namespace: default
spec:
  accessModes:
    ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: ptest

