kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc3
  namespace: default
spec:
  accessModes:
    ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: ptestest
