apiVersion: v1
kind: Service
metadata:
  name: svc_on_final_test_replica
  namespace: AMD_namespace
spec:
  type: NodePort
  selector:
    cpu: R9-7950X3D
    gpu: RX-7900-XTX
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001