apiVersion: v1
kind: Service
metadata:
  name: ipvs_test_service
spec:
  type: NodePort
  selector:
    app: ipvs_test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31415