apiVersion: v1
kind: Pod
metadata:
  name: ipvs_test_pod1
  label:
    app: ipvs_test
spec:
  containers:
  - name: nginx_ipvs_test
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]

  - name: curl_ipvs_test
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "while true; do sleep 30; curl http://localhost; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /data

  volumes:
  - name: shared-data
    hostPath:
      path: "./test_ipvs.html"
