apiVersion: v1
kind: Pod
metadata:
  name: ipvs_test_curl_pod
spec:
  containers:
  - name: curl_ipvs_test
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "while true; do sleep 30; curl http://localhost; done"]