apiVersion: v1
kind: Pod
metadata:
  name: pm_test_pod1
  labels:
    app: pm_test
  annotations:
    prometheus.io/scrapePorts: "2112"
spec:
  containers:
  - name: pod_metrics_ctr
    image: my_pod_metrics:latest
    # 该镜像是自定义的，构建逻辑在pkg/prometheus/pod_metrics_image目录下
    ports:
    - name: metrics
      containerPort: 2112

