apiVersion: "v1"
kind: Workflow
metadata:
  name: "ImageProcessWorkflow"
spec:
  entryNode: "ExtractImageMetadata"
  entryParams:
    "COUCHDB_URL": "http://admin:123@10.181.111.128:5984"
    "COUCHDB_DBNAME": "image"
    "IMAGE_NAME": "image.jpg"
    "IMAGE_DOCID": "image1"
    "COUCHDB_LOGDB": "logdb"
  nodes:
    ExtractImageMetadata:
      type: "func"
      funcNodeRef:
        metadata:
          name: "extractimagemetadata"
          namespace: "default"
        next: "Handler"
    Handler:
      type: "func"
      funcNodeRef:
        metadata:
          name: "handler"
          namespace: "default"
        next: "Thumbnail"
    Thumbnail:
      type: "func"
      funcNodeRef:
        metadata:
          name: "thumbnail"
          namespace: "default"
        next: ""
